// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
/// NOTE: This file must match the active Firebase project.
/// If you switch Firebase projects, re-run `flutterfire configure`
/// and select the new project to regenerate this file.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE7Y4O9B09FWxSuH80ny9bJ0khLCUmBbg',
    appId: '1:435024515863:web:151a6f7ac6b835911d1d52',
    messagingSenderId: '435024515863',
    projectId: 'aether-base-6741a',
    authDomain: 'aether-base-6741a.firebaseapp.com',
    storageBucket: 'aether-base-6741a.firebasestorage.app',
    measurementId: 'G-TXXRP3MXJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASBsvD7bjzKUp2XW8u4kJes-N_B3Fx4WQ',
    appId: '1:435024515863:android:cad7112c2c8129b81d1d52',
    messagingSenderId: '435024515863',
    projectId: 'aether-base-6741a',
    storageBucket: 'aether-base-6741a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV9mkvJzQIoRNKVeRR7FiJpxzYGObpe5s',
    appId: '1:435024515863:ios:1c8c81353787df8d1d1d52',
    messagingSenderId: '435024515863',
    projectId: 'aether-base-6741a',
    storageBucket: 'aether-base-6741a.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV9mkvJzQIoRNKVeRR7FiJpxzYGObpe5s',
    appId: '1:435024515863:ios:1c8c81353787df8d1d1d52',
    messagingSenderId: '435024515863',
    projectId: 'aether-base-6741a',
    storageBucket: 'aether-base-6741a.firebasestorage.app',
    iosBundleId: 'com.example.aether',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE7Y4O9B09FWxSuH80ny9bJ0khLCUmBbg',
    appId: '1:435024515863:web:50aa05a72df4584b1d1d52',
    messagingSenderId: '435024515863',
    projectId: 'aether-base-6741a',
    authDomain: 'aether-base-6741a.firebaseapp.com',
    storageBucket: 'aether-base-6741a.firebasestorage.app',
    measurementId: 'G-T5236BX1QH',
  );

}